version: '3'
services:
  gold_rate_api:
    build: ./gold_rate_api
    container_name: gold_rate_api
    image: gold_rate_api
    ports:
      - "8001:8000"
  
  exchange_rate_api:
    build: ./exchange_rate_api
    container_name: exchange_rate_api
    image: exchange_rate_api
    ports:
      - "8002:8000"